name: ci

on: push

jobs:
  publish-npm-and-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - run: npm install
      - id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - if: steps.publish.outputs.type != 'none'
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - if: steps.publish.outputs.type != 'none'
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - if: steps.publish.outputs.type != 'none'
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - if: steps.publish.outputs.type != 'none'
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            sineliu/kiwi:latest
            sineliu/kiwi:${{ steps.publish.outputs.version }}
